name: Check

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    uses: intisy/workflows/.github/workflows/test.yml@main
    with:
      node_version: '22'
      node_install: npm ci
      node_build: npm run typecheck
      node_test: npm test
      post_test: npm run preflight
